ERROR    root:test_fixture_run.py:15 有效值的成功测试